markdown: kramdown
highlighter: rouge

permalink: pretty

title: Shayan Abbasi
tagline: 'Econometrist & Data Scientist'
description: 'PhD Quantitative Marketing (McMaster) | Master of Financial Economics (BSE)'
url: https://shayanabbasi1995.github.io
# Use "" for user/org site (repo username.github.io). If site is at .../repo-name/, set baseurl: "/repo-name"
baseurl: ""

author:
  name: 'Shayan Abbasi'
  email: abbasi.shayan1995@gmail.com

paginate: 5

exclude:
  - README.md
  - LICENSE.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - ShayPic.jpg
